const SUMMARY_TYPE={
    GET_PRIORITY_TASKS:" GET_PRIORITY_TASKS",
    GET_PRIORITY_TASKS_LOADING:" GET_PRIORITY_TASKS_LOADING",
    GET_PRIORITY_TASKS_SUCCESS:" GET_PRIORITY_TASKS_SUCCESS",
    GET_PRIORITY_TASKS_ERROR:" GET_PRIORITY_TASKS_ERROR",
    GET_PRIORITY_TASKS_RESET:" GET_PRIORITY_TASKS_RESET",

    GET_STATUS_COUNTS:"GET_STATUS_COUNTS",
    GET_STATUS_COUNTS_LOADING:"GET_STATUS_COUNTS_LOADING",
    GET_STATUS_COUNTS_SUCCESS:"GET_STATUS_COUNTS_SUCCESS",
    GET_STATUS_COUNTS_ERROR:"GET_STATUS_COUNTS_ERROR",
    GET_STATUS_COUNTS_RESET:"GET_STATUS_COUNTS_RESET",

    GET_TASK_COUNTS:"GET_TASK_COUNTS",
    GET_TASK_COUNTS_LOADING:"GET_TASK_COUNTS_LOADING",
    GET_TASK_COUNTS_SUCCESS:"GET_TASK_COUNTS_SUCCESS",
    GET_TASK_COUNTS_ERROR:"GET_TASK_COUNTS_ERROR",
    GET_TASK_COUNTS_RESET:"GET_TASK_COUNTS_RESET",

    GET_WEEK_COUNTS:"GET_WEEK_COUNTS",
    GET_WEEK_COUNTS_LOADING:"GET_WEEK_COUNTS_LOADING",
    GET_WEEK_COUNTS_SUCCESS:"GET_WEEK_COUNTS_SUCCESS",
    GET_WEEK_COUNTS_ERROR:"GET_WEEK_COUNTS_ERROR",
    GET_WEEK_COUNTS_RESET:"GET_WEEK_COUNTS_RESET",


}

export default SUMMARY_TYPE ;