const SUMMARY_TYPE={
    GET_PRIORITY_TASKS:" GET_PRIORITY_TASKS",
    GET_PRIORITY_TASKS_LOADING:" GET_PRIORITY_TASKS_LOADING",
    GET_PRIORITY_TASKS_SUCCESS:" GET_PRIORITY_TASKS_SUCCESS",
    GET_PRIORITY_TASKS_ERROR:" GET_PRIORITY_TASKS_ERROR",
    GET_PRIORITY_TASKS_RESET:" GET_PRIORITY_TASKS_RESET",
}