export const preSales = {
    GET_ALL_PRESALES: "GET_ALL_PRESALES",
    GET_ALL_PRESALES_LOADING: "GET_ALL_PRESALES_LOADING",
    GET_ALL_PRESALES_SUCCESS: "GET_ALL_PRESALES_SUCCESS",
    GET_ALL_PRESALES_RESET: "GET_ALL_PRESALES_RESET",
    GET_ALL_PRESALES_ERROR: "GET_ALL_PRESALES_ERROR",
}

