const ReportTypes = {
    // get report
    GET_REPORT: "GET_REPORT",
    GET_REPORT_LOADING: "GET_REPORT_LOADING",
    GET_REPORT_SUCCESS: "GET_REPORT_SUCCESS",
    GET_REPORT_RESET: "GET_REPORT_RESET",
    GET_REPORT_ERROR: "GET_REPORT_ERROR",
}
export default ReportTypes;