const TIME_TRACKER_TYPES = {

    GET_TIME_TRACKER_FIRST:"GET_TIME_TRACKER_FIRST",
    GET_TIME_TRACKER_LOADING:"GET_TIME_TRACKER_LOADING",
    GET_TIME_TRACKER_SUCCESS:"GET_TIME_TRACKER_SUCCESS",
    GET_TIME_TRACKER_ERROR:"GET_TIME_TRACKER_ERROR",
    GET_TIME_TRACKER_RESET:"GET_TIME_TRACKER_RESET",

}

export default TIME_TRACKER_TYPES