const Addcomment = {

    ADD_COMMENT: "ADD_COMMENT",
    ADD_COMMENT_LOADING: "ADD_COMMENT_LOADING",
    ADD_COMMENT_SUCCESS: "ADD_COMMENT_SUCCESS",
    ADD_COMMENT_RESET: "ADD_COMMENT_RESET",
    ADD_COMMENT_ERROR: "ADD_COMMENT_ERROR",

    GET_COMMENT: "GET_COMMENT",
    GET_COMMENT_LOADING: "GET_COMMENT_LOADING",
    GET_COMMENT_SUCCESS: "GET_COMMENT_SUCCESS",
    GET_COMMENT_RESET: "GET_COMMENT_RESET",
    GET_COMMENT_ERROR: "GET_COMMENT_ERROR",


    DELETE_COMMENT: "DELETE_COMMENT",
    DELETE_COMMENT_LOADING: "DELETE_COMMENT_LOADING",
    DELETE_COMMENT_SUCCESS: "DELETE_COMMENT_SUCCESS",
    DELETE_COMMENT_RESET: "DELETE_COMMENT_RESET",
    DELETE_COMMENT_ERROR: "DELETE_COMMENT_ERROR",


    UPDATE_COMMENT: "UPDATE_COMMENT",
    UPDATE_COMMENT_LOADING: "UPDATE_COMMENT_LOADING",
    UPDATE_COMMENT_SUCCESS: "UPDATE_COMMENT_SUCCESS",
    UPDATE_COMMENT_RESET: "UPDATE_COMMENT_RESET",
    UPDATE_COMMENT_ERROR: "UPDATE_COMMENT_ERROR",

    GET_HISTORY: "GET_HISTORY",
    GET_HISTORY_LOADING: "GET_HISTORY_LOADING",
    GET_HISTORY_SUCCESS: "GET_HISTORY_SUCCESS",
    GET_HISTORY_ERROR: "GET_HISTORY_ERROR",
    GET_HISTORY_RESET: "GET_HISTORY_RESET",

    GET_BUGS: "GET_BUGS",
    GET_BUGS_LOADING: "GET_BUGS_LOADING",
    GET_BUGS_SUCCESS: "GET_BUGS_SUCCESS",
    GET_BUGS_ERROR: "GET_BUGS_ERROR",
    GET_BUGS_RESET: "GET_BUGS_RESET",


    GET_SUBTASK:"GET_SUBTASK",
    GET_SUBTASK_LOADING:"GET_SUBTASK_LOADING",
    GET_SUBTASK_SUCCESS:"GET_SUBTASK_SUCCESS",
    GET_SUBTASK_ERROR:"GET_SUBTASK_ERROR",
    GET_SUBTASK_RESET:"GET_SUBTASK_RESET",



    GET_USER_RECORD: 'GET_USER_RECORD',
    GET_USER_RECORD_LOADING: 'GET_USER_RECORD_LOADING',
    GET_USER_RECORD_SUCCESS: 'GET_USER_RECORD_SUCCESS',
    GET_USER_RECORD_ERROR: 'GET_USER_RECORD_ERROR',
    GET_USER_RECORD_RESET: 'GET_USER_RECORD_RESET',
}

export default Addcomment;