name: taskmanager CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Set execute permissions for deploy.sh
        run: chmod +x docker/app/deploy.sh
      - name: Build the Docker image
        run: |
          cd docker/app
          ./deploy.sh