const USERS_TYPES = {
    GET_ALL_USERS: 'GET_ALL_USERS',
    GET_ALL_USERS_LOADING: 'GET_ALL_USERS_LOADING',
    GET_ALL_USERS_SUCCESS: 'GET_ALL_USERS_SUCCESS',
    GET_ALL_USERS_ERROR: 'GET_ALL_USERS_ERROR',
    GET_ALL_USERS_RESET: 'GET_ALL_USERS_RESET',

    DELETE_USER: 'GET_DELETE_USER',
    GET_DELETE_USER_LOADING: 'GET_DELETE_USER_LOADING',
    GET_DELETE_USER_SUCCESS: 'GET_DELETE_USER_SUCCESS',
    GET_DELETE_USER_ERROR: 'GET_DELETE_USER_ERROR',
    GET_DELETE_USER_RESET: 'GET_DELETE_USER_RESET',

    CREATE_USER: 'CREATE_USER',
    CREATE_USER_LOADING: 'CREATE_USER_LOADING',
    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_ERROR: 'CREATE_USER_ERROR',
    CREATE_USER_RESET: 'CREATE_USER_RESET',

    GET_ALL_ROLES: 'GET_ALL_ROLES',
    GET_ALL_ROLES_LOADING: 'GET_ALL_ROLES_LOADING',
    GET_ALL_ROLES_SUCCESS: 'GET_ALL_ROLES_SUCCESS',
    GET_ALL_ROLES_ERROR: 'GET_ALL_ROLES_ERROR',
    GET_ALL_ROLES_RESET: 'GET_ALL_ROLES_RESET',
    
    GET_USER_LOGOUT_LEAVEREASON: 'GET_USER_LOGOUT_LEAVEREASON',
    GET_USER_LOGOUT_LEAVEREASON_LOADING: 'GET_USER_LOGOUT_LEAVEREASON_LOADING',
    GET_USER_LOGOUT_LEAVEREASON_SUCCESS: 'GET_USER_LOGOUT_LEAVEREASON_SUCCESS',
    GET_USER_LOGOUT_LEAVEREASON_ERROR: 'GET_USER_LOGOUT_LEAVEREASON_ERROR',
    GET_USER_LOGOUT_LEAVEREASON_RESET: 'GET_USER_LOGOUT_LEAVEREASON_RESET',
   

    // user login page time-------------------------------

    CREATE_USER_TIME: 'CREATE_USER_TIME',
    CREATE_USER_TIME_LOADING: 'CREATE_USER_TIME_LOADING',
    CREATE_USER_TIMESUCCESS: 'CREATE_USER_TIMESUCCESS',
    CREATE_USER_TIME_ERROR: 'CREATE_USER_TIME_ERROR',
    CREATE_USER_TIME_RESET: 'CREATE_USER_TIME_RESET',

    CREATE_USER_TIME_STOP: 'CREATE_USER_TIME_STOP',
    CREATE_USER_TIME_STOP_LOADING: 'CREATE_USER_TIME_STOP_LOADING',
    CREATE_USER_TIME_STOPSUCCESS: 'CREATE_USER_TIME_STOPSUCCESS',
    CREATE_USER_TIME_STOP_ERROR: 'CREATE_USER_TIME_STOP_ERROR',
    CREATE_USER_TIME_STOP_RESET: 'CREATE_USER_TIME_STOP_RESET',



    //user login page time--------------------------------
};

export default USERS_TYPES;
